// ======================================================================
// \title  RefTopologyAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for Ref topology
// ======================================================================

#ifndef Ref_RefTopologyAc_HPP
#define Ref_RefTopologyAc_HPP

#include "Drv/BlockDriver/BlockDriver.hpp"
#include "Drv/TcpClient/TcpClient.hpp"
#include "Ref/Control/Control.hpp"
#include "Ref/DoActions/DoActions.hpp"
#include "Ref/GetCtrlData/GetCtrlData.hpp"
#include "Ref/GetEnvData/GetEnvData.hpp"
#include "Ref/PingReceiver/PingReceiver.hpp"
#include "Ref/ProcessData/ProcessData.hpp"
#include "Ref/ProcessInData/ProcessInData.hpp"
#include "Ref/ProcessOutData/ProcessOutData.hpp"
#include "Ref/ProtectFromSunlight/ProtectFromSunlight.hpp"
#include "Ref/RecvBuffApp/RecvBuff.hpp"
#include "Ref/SendBuffApp/SendBuff.hpp"
#include "Ref/SetSensorState/SetSensorState.hpp"
#include "Ref/SignalGen/SignalGen.hpp"
#include "Ref/ThrDistribute/ThrDistribute.hpp"
#include "Ref/Top/RefTopologyDefs.hpp"
#include "Svc/ActiveLogger/ActiveLogger.hpp"
#include "Svc/ActiveRateGroup/ActiveRateGroup.hpp"
#include "Svc/AssertFatalAdapter/AssertFatalAdapter.hpp"
#include "Svc/BufferManager/BufferManager.hpp"
#include "Svc/CmdDispatcher/CommandDispatcher.hpp"
#include "Svc/CmdSequencer/CmdSequencer.hpp"
#include "Svc/Deframer/Deframer.hpp"
#include "Svc/FatalHandler/FatalHandler.hpp"
#include "Svc/FileDownlink/FileDownlink.hpp"
#include "Svc/FileManager/FileManager.hpp"
#include "Svc/FileUplink/FileUplink.hpp"
#include "Svc/Framer/Framer.hpp"
#include "Svc/Health/Health.hpp"
#include "Svc/LinuxTime/LinuxTime.hpp"
#include "Svc/PassiveConsoleTextLogger/PassiveTextLogger.hpp"
#include "Svc/PrmDb/PrmDb.hpp"
#include "Svc/RateGroupDriver/RateGroupDriver.hpp"
#include "Svc/StaticMemory/StaticMemory.hpp"
#include "Svc/SystemResources/SystemResources.hpp"
#include "Svc/TlmChan/TlmChan.hpp"

namespace Ref {

  // ----------------------------------------------------------------------
  // Constants
  // ----------------------------------------------------------------------

  namespace ConfigConstants {
    namespace cmdSeq {
      enum {
        BUFFER_SIZE = 5*1024
      };
    }
    namespace comm {
      enum {
        PRIORITY = 100,
        STACK_SIZE = Default::stackSize
      };
    }
    namespace fileDownlink {
      enum {
        TIMEOUT = 1000,
        COOLDOWN = 1000,
        CYCLE_TIME = 1000,
        FILE_QUEUE_DEPTH = 10
      };
    }
    namespace fileUplinkBufferManager {
      enum {
        STORE_SIZE = 3000,
        QUEUE_SIZE = 30,
        MGR_ID = 200
      };
    }
    namespace health {
      enum {
        WATCHDOG_CODE = 0x123
      };
    }
  }

  namespace BaseIds {
    enum {
      blockDrv = 0x100,
      rateGroup1Comp = 0x200,
      rateGroup2Comp = 0x300,
      rateGroup3Comp = 0x400,
      cmdDisp = 0x500,
      cmdSeq = 0x600,
      fileDownlink = 0x700,
      fileManager = 0x800,
      fileUplink = 0x900,
      pingRcvr = 0xA00,
      eventLogger = 0xB00,
      chanTlm = 0xC00,
      prmDb = 0xD00,
      control = 0xE00,
      health = 0x2000,
      SG1 = 0x2100,
      SG2 = 0x2200,
      SG3 = 0x2300,
      SG4 = 0x2400,
      SG5 = 0x2500,
      sendBuffComp = 0x2600,
      thrDistribute = 0x2700,
      comm = 0x4000,
      downlink = 0x4100,
      fatalAdapter = 0x4200,
      fatalHandler = 0x4300,
      fileUplinkBufferManager = 0x4400,
      linuxTime = 0x4500,
      rateGroupDriverComp = 0x4600,
      recvBuffComp = 0x4700,
      staticMemory = 0x4800,
      textLogger = 0x4900,
      uplink = 0x4A00,
      systemResources = 0x4B00,
      doActions = 0x4C00,
      setSensorState = 0x4D00,
      getEnvData = 0x4E00,
      processData = 0x4F00,
      processInData = 0x5000,
      processOutData = 0x5100,
      getCtrlData = 0x5200,
      protectFromSunlight = 0x5300,
    };
  }

  namespace InstanceIds {
    enum {
      SG1,
      SG2,
      SG3,
      SG4,
      SG5,
      blockDrv,
      chanTlm,
      cmdDisp,
      cmdSeq,
      comm,
      control,
      doActions,
      downlink,
      eventLogger,
      fatalAdapter,
      fatalHandler,
      fileDownlink,
      fileManager,
      fileUplink,
      fileUplinkBufferManager,
      getCtrlData,
      getEnvData,
      health,
      linuxTime,
      pingRcvr,
      prmDb,
      processData,
      processInData,
      processOutData,
      protectFromSunlight,
      rateGroup1Comp,
      rateGroup2Comp,
      rateGroup3Comp,
      rateGroupDriverComp,
      recvBuffComp,
      sendBuffComp,
      setSensorState,
      staticMemory,
      systemResources,
      textLogger,
      thrDistribute,
      uplink,
    };
  }

  namespace Priorities {
    enum {
      blockDrv = 140,
      chanTlm = 97,
      cmdDisp = 101,
      cmdSeq = 100,
      control = 100,
      eventLogger = 98,
      fileDownlink = 100,
      fileManager = 100,
      fileUplink = 100,
      pingRcvr = 100,
      prmDb = 96,
      rateGroup1Comp = 120,
      rateGroup2Comp = 119,
      rateGroup3Comp = 118,
    };
  }

  namespace QueueSizes {
    enum {
      SG1 = 10,
      SG2 = 10,
      SG3 = 10,
      SG4 = 10,
      SG5 = 10,
      blockDrv = 10,
      chanTlm = 10,
      cmdDisp = 20,
      cmdSeq = 10,
      control = 10,
      eventLogger = 10,
      fileDownlink = 30,
      fileManager = 30,
      fileUplink = 30,
      health = 25,
      pingRcvr = 10,
      prmDb = 10,
      rateGroup1Comp = 10,
      rateGroup2Comp = 10,
      rateGroup3Comp = 10,
      sendBuffComp = 10,
      thrDistribute = 10,
    };
  }

  namespace StackSizes {
    enum {
      blockDrv = 65536,
      chanTlm = 65536,
      cmdDisp = 65536,
      cmdSeq = 65536,
      control = 65536,
      eventLogger = 65536,
      fileDownlink = 65536,
      fileManager = 65536,
      fileUplink = 65536,
      pingRcvr = 65536,
      prmDb = 65536,
      rateGroup1Comp = 65536,
      rateGroup2Comp = 65536,
      rateGroup3Comp = 65536,
    };
  }

  namespace TaskIds {
    enum {
      blockDrv,
      chanTlm,
      cmdDisp,
      cmdSeq,
      control,
      eventLogger,
      fileDownlink,
      fileManager,
      fileUplink,
      pingRcvr,
      prmDb,
      rateGroup1Comp,
      rateGroup2Comp,
      rateGroup3Comp,
    };
  }

  // ----------------------------------------------------------------------
  // Component instances
  // ----------------------------------------------------------------------

  //! SG1
  extern SignalGen SG1;

  //! SG2
  extern SignalGen SG2;

  //! SG3
  extern SignalGen SG3;

  //! SG4
  extern SignalGen SG4;

  //! SG5
  extern SignalGen SG5;

  //! blockDrv
  extern Drv::BlockDriver blockDrv;

  //! chanTlm
  extern Svc::TlmChan chanTlm;

  //! cmdDisp
  extern Svc::CommandDispatcher cmdDisp;

  //! cmdSeq
  extern Svc::CmdSequencer cmdSeq;

  //! comm
  extern Drv::TcpClient comm;

  //! control
  extern Control control;

  //! doActions
  extern DoActions doActions;

  //! downlink
  extern Svc::Framer downlink;

  //! eventLogger
  extern Svc::ActiveLogger eventLogger;

  //! fatalAdapter
  extern Svc::AssertFatalAdapter fatalAdapter;

  //! fatalHandler
  extern Svc::FatalHandler fatalHandler;

  //! fileDownlink
  extern Svc::FileDownlink fileDownlink;

  //! fileManager
  extern Svc::FileManager fileManager;

  //! fileUplink
  extern Svc::FileUplink fileUplink;

  //! fileUplinkBufferManager
  extern Svc::BufferManager fileUplinkBufferManager;

  //! getCtrlData
  extern GetCtrlData getCtrlData;

  //! getEnvData
  extern GetEnvData getEnvData;

  //! health
  extern Svc::Health health;

  //! linuxTime
  extern Svc::LinuxTime linuxTime;

  //! pingRcvr
  extern PingReceiver pingRcvr;

  //! prmDb
  extern Svc::PrmDb prmDb;

  //! processData
  extern ProcessData processData;

  //! processInData
  extern ProcessInData processInData;

  //! processOutData
  extern ProcessOutData processOutData;

  //! protectFromSunlight
  extern ProtectFromSunlight protectFromSunlight;

  //! rateGroup1Comp
  extern Svc::ActiveRateGroup rateGroup1Comp;

  //! rateGroup2Comp
  extern Svc::ActiveRateGroup rateGroup2Comp;

  //! rateGroup3Comp
  extern Svc::ActiveRateGroup rateGroup3Comp;

  //! rateGroupDriverComp
  extern Svc::RateGroupDriver rateGroupDriverComp;

  //! recvBuffComp
  extern RecvBuff recvBuffComp;

  //! sendBuffComp
  extern SendBuff sendBuffComp;

  //! setSensorState
  extern SetSensorState setSensorState;

  //! staticMemory
  extern Svc::StaticMemory staticMemory;

  //! systemResources
  extern Svc::SystemResources systemResources;

  //! textLogger
  extern Svc::PassiveTextLogger textLogger;

  //! thrDistribute
  extern ThrDistribute thrDistribute;

  //! uplink
  extern Svc::Deframer uplink;

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  //! Initialize components
  void initComponents(
      const TopologyState& state //!< The topology state
  );

  //! Configure components
  void configComponents(
      const TopologyState& state //!< The topology state
  );

  //! Set component base Ids
  void setBaseIds();

  //! Connect components
  void connectComponents();

  //! Register commands
  void regCommands();

  //! Read parameters
  void readParameters();

  //! Load parameters
  void loadParameters();

  //! Start tasks
  void startTasks(
      const TopologyState& state //!< The topology state
  );

  //! Stop tasks
  void stopTasks(
      const TopologyState& state //!< The topology state
  );

  //! Free threads
  void freeThreads(
      const TopologyState& state //!< The topology state
  );

  //! Tear down components
  void tearDownComponents(
      const TopologyState& state //!< The topology state
  );

  // ----------------------------------------------------------------------
  // Setup and teardown functions
  // ----------------------------------------------------------------------

  //! Set up the topology
  void setup(
      const TopologyState& state //!< The topology state
  );

  //! Tear down the topology
  void teardown(
      const TopologyState& state //!< The topology state
  );

}

#endif
